networks:
  wss-network:
    name: wss-network
    driver: bridge

services:
  wss-app:
    build:
      context: .
      dockerfile: docker/dockerfile
    container_name: ${DOCKER_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${DOCKER_EXPOSE_PORT}:${PORT}
      - ${DOCKER_EXPOSE_WEBSOCKET_PORT}:${WEBSOCKET_PORT}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./channels:/app/channels
      - ./db:/app/db
      - ./.env:/app/.env
    networks:
      - wss-network
